export const AUTHENTICATION_SCREEN = "AUTHENTICATION_SCREEN";
export const REGISTER_SCREEN = "REGISTER_SCREEN";
export const PASSWORD_RESET_SCREEN = "PASSWORD_RESET_SCREEN";
export const MAIN_SCREEN = "MAIN_SCREEN";
export const PRICE_DETAIL_SCREEN = "PRICE_DETAIL_SCREEN";
export const PRODUCT_DETAIL_SCREEN = "PRODUCT_DETAIL_SCREEN";

export const PROFILE_SCREEN = "PROFILE_SCREEN";
export const MY_SHOP_CLIENTS_SCREEN = "MY_SHOP_CLIENTS_SCREEN";
export const CLIENT_INFO_SCREEN = "CLIENT_INFO_SCREEN";
export const MY_PROFILE_SCREEN = "MY_PROFILE_SCREEN";
export const STANDARD_COMMENT_SCREEN = "STANDARD_COMMENT_SCREEN";

export const ORDER_DETAIL_SCREEN = "ORDER_DETAIL_SCREEN";
export const ORDER_DETAIL_SECOND_SCREEN = "ORDER_DETAIL_SECOND_SCREEN";
export const COOP_PURCHASES_SCREEN = "COOP_PURCHASES_SCREEN";
export const COOP_PRICE_DETAIL_SCREEN ="COOP_PRICE_DETAIL_SCREEN";
export const COOP_ORDER_DETAIL_SCREEN = "COOP_ORDER_DETAIL_SCREEN";
export const COOP_PRODUCT_DETAIL_SCREEN = "COOP_PRODUCT_DETAIL_SCREEN";
export const USER_AGREEMENT_SCREEN = "USER_AGREEMENT_SCREEN";
export const ALL_ORDER_SCREEN = "ALL_ORDER_SCREEN";
export const ALL_ORDER_DETAIL_SCREEN = "ALL_ORDER_DETAIL_SCREEN";
export const GROUP_SCREEN = "GROUP_SCREEN";

export const SHOPS_SCREEN = "SHOPS_SCREEN";
export const SHOP_INFO_SCREEN = "SHOP_INFO_SCREEN";
export const SHOP_SEARCH_RESULT_SCREEN = "SHOP_SEARCH_RESULT_SCREEN";

export const CONTACT_SCREEN = "CONTACT_SCREEN";
export const CATEGORY_SCREEN = "CATEGORY_SCREEN";

export const AUTHENTICATION_STACK = "AUTHENTICATION_STACK";
export const REGISTER_STACK = "REGISTER_STACK";
export const PASSWORD_RESET_STACK = "PASSWORD_RESET_STACK";
export const MAIN_STACK = "MAIN_STACK";
export const SHOPS_STACK = "SHOPS_STACK";

export const CART_STACK = "CART_STACK";
export const CART_SCREEN = "CART_SCREEN";

export const NOTIFICATION_STACK = "NOTIFICATION_STACK";
export const NOTIFICATIONS_SCREEN = "NOTIFICATIONS_SCREEN";

export const TAB_NAVIGATOR = "TAB_NAVIGATOR";

export const BAR_CODE_SCANNER_SCREEN = "BAR_CODE_SCANNER_SCREEN";

export const SELECT_DELIVERY_SCREEN = "SELECT_DELIVERY_SCREEN";
export const SELECT_ADDRESS_SCREEN = "SELECT_ADDRESS_SCREEN";
export const SELECT_PAYMENT_SCREEN = "SELECT_PAYMENT_SCREEN";
export const ADD_ADDRESS_SCREEN = "ADD_ADDRESS_SCREEN";

export const SBER_BANK_STACK = "SBER_BANK_STACK";
export const SBERBANK_PAYMENT_SCREEN = "SBERBANK_PAYMENT_SCREEN";

export const CHOOSE_STAFF_SHOPS_CHAT_SCREEN = "CHOOSE_STAFF_SHOPS_CHAT_SCREEN";
export const ACTIVE_CHAT_SCREEN = 'ACTIVE_CHAT_SCREEN';
export const MAIN_CHAT_LIST_SCREEN = 'MAIN_CHAT_LIST_SCREEN';
export const SHOP_CHAT_LIST_SCREEN = 'SHOP_CHAT_LIST_SCREEN';
export const IMAGE_FULL_SCREEN = 'IMAGE_FULL_SCREEN';
export const CONTACTS_SCREEN = 'CONTACTS_SCREEN';
export const REC_SHOPS_SCREEN = "REC_SHOPS_SCREEN";